[env]
# Environment variables
DOTFILES_DIR = "{{ cwd }}"
HOME_DIR = "{{ env.HOME }}"
CLAUDE_CONFIG_DIR = "{{ env.HOME }}/.claude"

# Colors for output
RED = "\\033[0;31m"
GREEN = "\\033[0;32m"
YELLOW = "\\033[1;33m"
BLUE = "\\033[0;34m"
NC = "\\033[0m"

# Files to manage
DOTFILES = ".bashrc .tmux.conf .bash_profile .wezterm.lua"