#!/bin/bash

git worktree list --porcelain | while IFS= read -r line; do
    if [[ $line == worktree* ]]; then
        worktree_path=${line#worktree }
        worktree_name=$(basename "$worktree_path")
        printf "%-20s" "$worktree_name"
    elif [[ $line == branch* ]]; then
        branch_name=${line#branch refs/heads/}
        printf "%-20s" "($branch_name)"
    elif [[ $line == HEAD* ]]; then
        commit_hash=${line#HEAD }
        printf "%s" "${commit_hash:0:8}"
    elif [[ -z $line ]]; then
        echo
    fi
done