
[terminal.shell]
program = "/bin/bash"

[general]
# Alacritty Configuration (TOML format)

import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
    # Other available themes:
    # "~/.config/alacritty/catppuccin-macchiato.toml"
    # "~/.config/alacritty/catppuccin-frappe.toml"
    # "~/.config/alacritty/catppuccin-latte.toml"
]

[font]
size = 14.0

# [window]
# decorations = "none"
# startup_mode = "Fullscreen"

[env]
TERM = "xterm-256color"

[terminal]
